import { Question } from './question';
import { Vocubulary } from './vocabulary';

export const Words: Vocubulary[] = [
  {
    id: 1,
    translation_french: 'Porte',
    singular_arabic: 'باب',
    plural_arabic: 'ابواب',
  },
  {
    id: 2,
    translation_french: 'Maison',
    singular_arabic: 'دار',
    plural_arabic: 'ديار',
  },
  {
    id: 3,
    translation_french: 'Livre',
    singular_arabic: 'كتاب',
    plural_arabic: 'كتب',
  },
  {
    id: 4,
    translation_french: 'Lit',
    singular_arabic: 'سرير',
    plural_arabic: 'سرر',
  },
  {
    id: 5,
    translation_french: 'Vêtement',
    singular_arabic: 'لباس',
    plural_arabic: 'البسة',
  },
  {
    id: 6,
    translation_french: 'Montagne',
    singular_arabic: 'جبل',
    plural_arabic: 'جبال',
  },
  {
    id: 7,
    translation_french: 'Mosquée',
    singular_arabic: 'مسجد',
    plural_arabic: 'مساجد',
  },
  {
    id: 8,
    translation_french: 'Outil',
    singular_arabic: 'اداة',
    plural_arabic: 'ادوات',
  },
  {
    id: 9,
    translation_french: 'Main',
    singular_arabic: 'يد',
    plural_arabic: 'ايد',
  },
  {
    id: 10,
    translation_french: 'Lune',
    singular_arabic: 'قمر',
    plural_arabic: '',
  },
  {
    id: 11,
    translation_french: 'Pleine lune',
    singular_arabic: 'بدر',
    plural_arabic: '',
  },
  {
    id: 12,
    translation_french: 'Croissant de lune',
    singular_arabic: 'هلال',
    plural_arabic: '',
  },
  {
    id: 13,
    translation_french: 'Le soleil',
    singular_arabic: 'الشمس',
    plural_arabic: '',
  },
  {
    id: 14,
    translation_french: 'Fruit',
    singular_arabic: 'فاكهة',
    plural_arabic: 'فواكه',
  },
  {
    id: 15,
    translation_french: 'Drapeau/signe/slogan',
    singular_arabic: 'علم',
    plural_arabic: 'اعلام',
  },
  {
    id: 16,
    translation_french: 'Boite/coffre',
    singular_arabic: 'صندوق',
    plural_arabic: 'صناديق',
  },
  {
    id: 17,
    translation_french: 'Elève homme',
    singular_arabic: 'تلميذ',
    plural_arabic: 'تلاميذ',
  },
  {
    id: 18,
    translation_french: 'Elève femme',
    singular_arabic: 'تلميذة',
    plural_arabic: 'تلميذات',
  },
  {
    id: 19,
    translation_french: 'Attentif/discipliné',
    singular_arabic: 'مهذب',
    plural_arabic: '',
  },
  {
    id: 20,
    translation_french: 'Le départ',
    singular_arabic: 'الذهاب',
    plural_arabic: '',
  },
  {
    id: 21,
    translation_french: 'Le rendez-vous',
    singular_arabic: 'الميعاد',
    plural_arabic: '',
  },
  {
    id: 22,
    translation_french: 'Ecole',
    singular_arabic: 'مدرسة',
    plural_arabic: 'مدارس',
  },
  {
    id: 23,
    translation_french: 'Enseignant',
    singular_arabic: 'معلم',
    plural_arabic: 'معلمون',
  },
  {
    id: 24,
    translation_french: 'Enseignant/Maitre',
    singular_arabic: 'استاذ',
    plural_arabic: 'اساتذة',
  },
  {
    id: 25,
    translation_french: 'Cours',
    singular_arabic: 'درس',
    plural_arabic: 'دروس',
  },
  {
    id: 26,
    translation_french: 'Le retour',
    singular_arabic: 'الرجوع',
    plural_arabic: '',
  },
  {
    id: 27,
    translation_french: 'Famille',
    singular_arabic: 'اسرة',
    plural_arabic: '',
  },
  {
    id: 28,
    translation_french: 'Prière du matin',
    singular_arabic: 'الصبح',
    plural_arabic: '',
  },
  {
    id: 29,
    translation_french: 'Prière du midi',
    singular_arabic: 'الظهر',
    plural_arabic: '',
  },
  {
    id: 30,
    translation_french: "Prière de l'après-midi",
    singular_arabic: 'العصر',
    plural_arabic: '',
  },
  {
    id: 31,
    translation_french: 'Prière du soir',
    singular_arabic: 'المغرب',
    plural_arabic: '',
  },
  {
    id: 32,
    translation_french: 'Prière de la nuit',
    singular_arabic: 'العشاء',
    plural_arabic: '',
  },
  {
    id: 33,
    translation_french: 'Frère',
    singular_arabic: 'اخ',
    plural_arabic: 'إخوة',
  },
  {
    id: 34,
    translation_french: 'Père',
    singular_arabic: 'اب',
    plural_arabic: 'اباء',
  },
  {
    id: 35,
    translation_french: 'Mère',
    singular_arabic: 'امّ',
    plural_arabic: 'امّهات',
  },
  {
    id: 36,
    translation_french: 'Printemps',
    singular_arabic: 'الربيع',
    plural_arabic: '',
  },
  {
    id: 37,
    translation_french: 'Eté',
    singular_arabic: 'الصيف',
    plural_arabic: '',
  },
  {
    id: 38,
    translation_french: 'Automne',
    singular_arabic: 'الخريف',
    plural_arabic: '',
  },
  {
    id: 39,
    translation_french: 'Hiver',
    singular_arabic: 'الشتاء',
    plural_arabic: '',
  },
  {
    id: 40,
    translation_french: 'Bienfait',
    singular_arabic: 'نعمة',
    plural_arabic: 'نعم',
  },
  {
    id: 41,
    translation_french: 'Epreuve',
    singular_arabic: 'امتحان',
    plural_arabic: 'امتحانات',
  },
  {
    id: 42,
    translation_french: 'Pain',
    singular_arabic: 'خبز',
    plural_arabic: 'اخباز',
  },
  {
    id: 43,
    translation_french: 'Enfant',
    singular_arabic: 'طفل',
    plural_arabic: 'اطفال',
  },
  {
    id: 44,
    translation_french: 'Vacances',
    singular_arabic: 'عطلة',
    plural_arabic: 'عطلات',
  },
  {
    id: 45,
    translation_french: 'Musulman',
    singular_arabic: 'مسلم',
    plural_arabic: 'مسلمون',
  },
  {
    id: 46,
    translation_french: 'Musulmane',
    singular_arabic: 'مسلمة',
    plural_arabic: 'مسلمات',
  },
  {
    id: 47,
    translation_french: 'Soeur',
    singular_arabic: 'اخت',
    plural_arabic: 'اخوات',
  },
  {
    id: 48,
    translation_french: 'Viande',
    singular_arabic: 'لحم',
    plural_arabic: 'لحوم',
  },
];

export const Questions: Question[] = [
  {
    id: 1,
    question_text: 'Traduisez ce mot en français: "اخ" ?',
    correctAnswerId: 1,
    answers: [
      { id: 1, answer_text: 'Frère' },
      { id: 2, answer_text: 'Père' },
      { id: 3, answer_text: 'Mère' },
      { id: 4, answer_text: 'Soeur' },
    ],
  },
  {
    id: 2,
    question_text: 'Traduisez ce mot en français: "إخوة" ?',
    correctAnswerId: 3,
    answers: [
      { id: 1, answer_text: 'Père' },
      { id: 2, answer_text: 'Soeur' },
      { id: 3, answer_text: 'Frère' },
      { id: 4, answer_text: 'Mère' },
    ],
  },
];
